/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'id' : IDL.Nat,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'loginStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'loginStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };